create table IF NOT EXISTS USERS (
    ID                      bigint generated by default as identity,
    USERNAME                varchar(128),
    PASSWORD                varchar(128),
    USER_TYPE_ID            number,
    ADDRESS                 varchar(128),
    REGISTRATION_DOCUMENT   varchar(64),
    UPDATED_AT              date,
    INSERTED_AT             date,
    RESTAURANT_ID           bigint,
    STATUS                  boolean
);

create table IF NOT EXISTS USER_TYPE (
    ID                          bigint generated by default as identity,
    DESCRIPTION                 varchar(32)
);

insert into USERS(ID, USERNAME, PASSWORD, USER_TYPE_ID, ADDRESS, REGISTRATION_DOCUMENT, UPDATED_AT,INSERTED_AT,RESTAURANT_ID,STATUS) values (-99,'admin','c504380676f88186',2,'xxx','xx',null,null,null,true);

insert into USER_TYPE(ID, DESCRIPTION ) values (1,'Client');
insert into USER_TYPE(ID, DESCRIPTION) values (2,'Owner');

create table IF NOT EXISTS RESTAURANT (
    ID                          bigint generated by default as identity,
    RESTAURANT_NAME         varchar(128) NOT NULL,
    ADDRESS                 varchar(128) NOT NULL,
    WORK_TIME               varchar(16) NOT NULL,
    RESTAURANT_IMAGE        CLOB,
    UPDATED_AT              date,
    INSERTED_AT             date
);

create table IF NOT EXISTS ITEM (
    ID                      bigint generated by default as identity,
    ITEM_NAME               varchar(128) NOT NULL,
    DESCRIPTION             varchar(600)NOT NULL,
    PRICE                   number NOT NULL,
    STATUS                  boolean,
    RESTAURANT_ID           number not null,
    ITEM_IMAGE              CLOB,
    UPDATED_AT              date,
    INSERTED_AT             date
);

create table IF NOT EXISTS ADDITIONAL_ITEM (
    ID                      bigint generated by default as identity,
    ADDITIONAL_ITEM_NAME    varchar(128) NOT NULL,
    DESCRIPTION             varchar(600)NOT NULL,
    PRICE                   number NOT NULL,
    STATUS                  boolean,
    ITEM_ID                 number not null,
    ADDITIONAL_ITEM_IMAGE   CLOB,
    UPDATED_AT              date,
    INSERTED_AT             date
);

create table IF NOT EXISTS ITEM_ACQUISITION_REL (
    ID                      bigint generated by default as identity,
    ITEM_ID                 number NOT NULL,
    ACQUISITION_ID          number NOT NULL,
    DESCRIPTION             varchar(600) NOT NULL,
    UPDATED_AT              date,
    INSERTED_AT             date
);

create table IF NOT EXISTS ADDITIONAL_ITEM_REL (
    ID                      bigint generated by default as identity,
    ADDITIONAL_ITEM_ID      number,
    ITEM_ACQUISITION_REL_ID number,
    UPDATED_AT              date,
    INSERTED_AT             date
);

create table IF NOT EXISTS ACQUISITION (
    ID                      bigint generated by default as identity,
    CLIENT_ID               number,
    PRICE                   number,
    DESCRIPTION             varchar(600),
    UPDATED_AT              date,
    INSERTED_AT             date
);